# Propagation of correlations in MCMC

## Introduction

It was pointed out that the integration can not be separated for correlated parameters. Below we briefly summarize the idea. From Bayes' theorem, 

$$\pi(m_{\nu}, \vec{\alpha}, \theta_{1}, \theta_{2} | y_1, y_2) \propto \pi(y_1, y_2 | m_{\nu}, \vec{\alpha}, \theta_{1}, \theta_{2}) \cdot \pi(m_{\nu}, \vec{\alpha}, \theta_{1}, \theta_{2}).$$

Here, $\pi$ is the probability distribution, $m_\nu$ is the parameter of interest, $\vec{\alpha}$ are the shared or independent parameters, $y_1$ and $y_2$ are the two separated measurements, each with a nuisance parameter $\theta_1$ and $\theta_{2}$. These two nuisance parameters are partly correlated, with a correlation coefficient $\rho$, mean values $\mu_1, \mu_2$ and standard errors $\sigma_1, \sigma_2$ separately.

Ideally, to obtain information for marginal posterior distribution of $m_\nu$, a multi-dimensional integration over $\vec{\alpha}, \theta_1$ and $\theta_2$ is required. If, however, $\theta_{1}$ and $\theta_{2}$ have partial correlation, the integration over $\theta_1$ and $\theta_2$ is not separable. In a Markov Chain sampling, this indicates that a separated sampling in sequence might not be possible for partly correlated parameters.

## An analytical solution

Under a specific case of multivariate normal distribution for both priors and posteriors, the integration might be calculated analytically regardless of the correlations. Usually, to avoid multiple usage of the same data set, the calibration runs determining $\theta_1$ and $\theta_2$ are separated from the main measurements. That is to say, the prior on $\theta_1$ and $\theta_2$ are usually uncorrelated with the other parameters. Therefore,

$$\pi(m_{\nu}, \vec{\alpha}, \theta_{1}, \theta_{2}) = \pi(m_{\nu})\cdot\pi(\vec{\alpha})\cdot\pi(\theta_1, \theta_2),$$

where 
$$\pi(\theta_1, \theta_2) \sim \pi (\mu_1, \mu_2; \sigma_1, \sigma_2, \rho_{12})$$ are the calibration results.

Rewrite

$$\pi(\theta_1, \theta_2) = \pi(\theta_1) \cdot \pi(\theta_2 | \theta_1),$$

and also note that

$$\pi(y_1, y_2 | m_{\nu}, \vec{\alpha}, \theta_{1}, \theta_{2}) = \pi(y_1 | m_{\nu}, \vec{\alpha}, \theta_{1}) \cdot \pi(y_2 | m_{\nu}, \vec{\alpha}, \theta_{2}),$$

we have

$$\pi(m_{\nu}, \vec{\alpha}, \theta_{1}, \theta_{2} | y_1, y_2) \propto \pi(m_{\nu}, \vec{\alpha}, \theta_{1} | y_1) \cdot \pi(\theta_2 | \theta_1) \cdot \pi(y_2 | m_{\nu}, \vec{\alpha}, \theta_{2}).$$

Here we used the fact that

$$\pi(m_{\nu}, \vec{\alpha}, \theta_{1} | y_1) \propto \pi(y_1 | m_{\nu}, \vec{\alpha}, \theta_{1}) \cdot \pi(m_{\nu}) \cdot \pi(\vec{\alpha}) \cdot \pi(\theta_1).$$

From this expression, the joint probability distribution of all parameters can be derived by sampling the second measurement with prior

$$\pi(m_{\nu}, \vec{\alpha}, \theta_{1} | y_1) \cdot \pi(\theta_2 | \theta_1)$$.

Now we want to get rid of $\theta_1$ from the sampling of second measurement, since it only affects prior and has no impact on the likelihood function. That means we want to evaluate

$$P = \int_{\theta_1} \pi(m_{\nu}, \vec{\alpha}, \theta_{1} | y_1) \cdot \pi(\theta_2 | \theta_1) d\theta_1.$$

From the sampling of first measurement, we obtain

$$\pi(m_{\nu}, \vec{\alpha}, \theta_{1} | y_1) \sim \textit{N}(\vec{M}, \Sigma).$$

The conditional distribution based on a multivariate normal distribution can be expressed as

$$\pi(\theta_2 | \theta_1) \sim \textit{N}\left( \mu_2 + (\theta_1-\mu_1)\cdot \rho_{12} \frac{\sigma_2}{\sigma_1}, \sigma_2\sqrt{1 - \rho_{12}^2}\right),$$

Since $P$ is given by a convolution of two (multi)variate normal distributions, $P$ itself also follows a normal distribution $N(\vec{M^{'}}, \Sigma^{'})$. In the following we will evaluate $\vec{M^{'}}$ and $\Sigma^{'}$ in explicit forms, but not in a mathematically rigorous approach. Any complementary work to provide a proof / precise computation would be greatly appreciated.

### Mean and sigma values of the $\theta_2$ prior

It is obvious that the new normal distribution has the same mean and sigma values for parameters $m_\nu$ and $\vec{\alpha}$, but has a different mean and sigma for $\theta_2$. Without a solid proof, since $\theta_2$ only has its dependency on $\theta_1$ from calibration, its explicit prior should be independent of the measured $m_\nu$ and $\vec{\alpha}$, and their correlations with $\theta_1$. This can be understood as taking $\theta_2$ as the parameter of interest, and the integration over $m_\nu$ and $\vec{\alpha}$ should have no impact on the $\theta_2$ distribution. Therefore, its form only depends on the calibration measurements and main measurements of $\theta_1$,

$$ P \sim \int_{\theta_1} \exp\left\{-\frac{1}{2}\cdot\left[\frac{(\theta_1-\hat{\theta_1})^2}{\hat{\sigma_1}^2}+\frac{(\theta_2-\mu_2-(\theta_1-\mu_1)\cdot \rho_{12} \frac{\sigma_2}{\sigma_1})^2}{\sigma_2^2(1-\rho_{12}^2)}\right]\right\}d\theta_1$$

Note that $M_1 = \hat{\theta_1}$ is the estimated mean value from main measurement, while $\mu_1$ is the estimated mean value for the same parameter but from calibration measurement. 

The expression above is a standard exponential integration, and is evaluated to be (up to a normalization constant):

$$P \sim \exp\, \left\{ -\frac{1}{2\left[ \hat{\sigma_1}^2\rho_{12}^2\frac{\sigma_2^2}{\sigma_1^2} + \sigma_2^2(1-\rho_{12}^2) \right]} \left[\theta_2 - \mu_2 + (\mu_1-\hat{\theta_1})\rho_{12}\frac{\sigma_2}{\sigma_1} \right]^2\right\}$$

Therefore we have

$$\sigma_2^{'2} = \hat{\sigma_1}^2\rho_{12}^2\frac{\sigma_2^2}{\sigma_1^2} + \sigma_2^2(1-\rho_{12}^2)$$

and

$$\mu_2^{'} = \mu_2 - (\mu_1 - \hat{\theta_1})\rho_{12}\frac{\sigma_2}{\sigma_1}.$$

### Correlation coefficient of $\theta_2$ and $m_\nu$

It is expected that the correlation of $\theta_2$ and $m_\nu$ (or any of $\alpha$'s) does not depend on any other parameter, except for $\theta_1$. Therefore for simplicity we only work in the 3-parameter case ($\theta_2$, $m_\nu$ and $\theta_1$), and the formula is expected to also hold for the general case. (Proof might be required!) The multivariate normal distribution from first measurement, $\textit{N}(\vec{M}, \Sigma)$, reduces to a bivariate form,

$$\textit{N}(\vec{M}, \Sigma) \sim \exp \left[ -\frac{1}{2(1-\rho_{m1}^2)}\cdot \left( \frac{m_\nu^2}{\hat{\sigma_m}^2} - 2\rho_{m1} \frac{\theta_1m_\nu}{\hat{\sigma_m}\hat{\sigma_1}} + \frac{\theta_1^2}{\hat{\sigma_1}^2}\right)\right].$$

With this, the integration becomes

$$P \sim \int \exp\left[ -\frac{1}{2(1-\rho_{m1}^2)}\cdot \left( \frac{m_\nu^2}{\hat{\sigma_m}^2} - 2\rho_{m1} \frac{\theta_1m_\nu}{\hat{\sigma_m}\hat{\sigma_1}} + \frac{\theta_1^2}{\hat{\sigma_1}^2}\right)\right] \exp \left\{ -\frac{\left[\theta_2 - \mu_2 - (\theta_1-\mu_1)\rho_{12} \frac{\sigma_2}{\sigma_1}\right]^2}{2\sigma_2^2(1-\rho_{12}^2)}\right\}d\theta_1.$$

This expression seems horrible. But we already know that, the correlation coefficient does not scale with the variance and the mean value of the measurement. Therefore, we can simplify the expression (only for the purpose of obtaining correlation) by assuming $\hat{\sigma_m}=\hat{\sigma_1}=\sigma_1=\sigma_2=1$, $\mu_1=\mu_2=0.$ Now the integration yields

$$P \sim \exp \,\left\{ -\frac{m_\nu^2}{2(1-\rho_{m1}^2)}-\frac{\theta_2^2}{2(1-\rho_{12}^2)} + \frac{\left(\frac{\rho_{m1}m_\nu}{1-\rho_{m1}^2} + \frac{\rho_{12}\theta_2}{1-\rho_{12}^2}\right)^2}{4\left[\frac{1}{2(1-\rho_{m1}^2)}+\frac{\rho_{12}^2}{2(1-\rho_{12}^2)}\right]} \right\}.$$

This should be equivalent to a bivariate normal distribution in between $m_\nu$ and $\theta_2$ with correlation coefficient $\rho_{m2}$. Therefore,

$$-\frac{1}{2(1-\rho_{m2}^2)} = -\frac{1}{2(1-\rho_{m1}^2)} + \left.\left( \frac{\rho_{m1}}{1-\rho_{m1}^2}\right)^2 \middle/ 2\left( \frac{1}{1-\rho_{m1}^2} + \frac{\rho_{12}^2}{1-\rho_{12}^2} \right) \right. .$$

Simplifying this we get

$$\rho_{m2}^2 = \rho_{12}^2 \rho_{m1}^2$$

With this we almost obtained an expression for $\rho_{m2}$, except for its sign. This can be derived by a very simple example: if $\theta_1$ and $\theta_2$ are fully correlated, we know that $\rho_{m2} = \rho_{m1}$. Therefore the sign is chosen such that

$$\rho_{m2} = \rho_{m1} \cdot \rho_{12}.$$

# A toy MC study

Here we perform a toy Monte Carlo study to prove that performing a sequential sampling with the method above yields an equivalent result with combined sampling. Emcee is used as the sampler.

In [1]:
import numpy as np

# We perform the test in 4 dimensions (a, b, c, d), where (a, b) 
# are shared parameters for two separate measurements, c is a nuisance
# parameter affecting measurement 1, d is the same parameter (not 
# necessarily having the same value) affecting measurement 2.
# There is another calibration measurement on (c, d).

# Generate a "true" correlation for (a, b, c, d).
from scipy.stats import random_correlation
ndim = 4
eigs_rnd = np.random.rand(ndim)
corr = random_correlation.rvs(eigs=eigs_rnd / np.sum(eigs_rnd) * ndim)
#print("Generated correlation matrix: \n", corr, "\n", sep="")

# Generate a "true" mean value for (a, b, c, d).
mean = np.random.rand(ndim)*10
#print("Generated mean values: \n", mean, "\n", sep="")

# Generate measurement 1, 2 and calibration. To make it realistic,
# measurements have less sensitivity on (c, d) compared with calibration.

uncertainty_1 = np.random.normal(3, 0.3, ndim-1) # measurements on (a, b, c)
uncertainty_2 = np.random.normal(2, 0.2, ndim-1) # measurements on (a, b, d)
uncertainty_c = np.random.normal(1, 0.1, 2) # measurement on (c, d)


# To make it clear, we separate each campaign.
# Measurement 1
dim_1 = [0, 1, 2]
corr_1 = np.zeros((len(dim_1), len(dim_1)))
for i, index_i in enumerate(dim_1):
    for j, index_j in enumerate(dim_1):
        corr_1[i][j] = corr[index_i][index_j]
        
cov_1 = np.array([np.multiply(corr_row, uncertainty_1)*uncertainty_1[index] for index, corr_row in enumerate(corr_1)])
mean_1 = np.random.multivariate_normal(mean=[mean[i] for i in dim_1], cov=cov_1, size=1)[0]

print("Generated measurement 1 has mean value: \n", mean_1, "\n\nand covariance matrix: \n", cov_1, "\n", sep="")

# Measurement 2
dim_2 = [0, 1, 3]
corr_2 = np.zeros((len(dim_1), len(dim_1)))
for i, index_i in enumerate(dim_2):
    for j, index_j in enumerate(dim_2):
        corr_2[i][j] = corr[index_i][index_j]
        
cov_2 = np.array([np.multiply(corr_row, uncertainty_2)*uncertainty_2[index] for index, corr_row in enumerate(corr_2)])
mean_2 = np.random.multivariate_normal(mean=[mean[i] for i in dim_2], cov=cov_2, size=1)[0]

print("Generated measurement 2 has mean value: \n", mean_2, "\n\nand covariance matrix: \n", cov_2, "\n", sep="")

# Calibration
dim_c = [2, 3]
corr_c = np.zeros((len(dim_c), len(dim_c)))
for i, index_i in enumerate(dim_c):
    for j, index_j in enumerate(dim_c):
        corr_c[i][j] = corr[index_i][index_j]

cov_c = np.array([np.multiply(corr_row, uncertainty_c)*uncertainty_c[index] for index, corr_row in enumerate(corr_c)])
mean_c = np.random.multivariate_normal(mean=[mean[i] for i in dim_c], cov=cov_c, size=1)[0]

#print("Generated calibration has mean value: \n", mean_c, "\n\nand covariance matrix: \n", cov_c, "\n", sep="")

Generated measurement 1 has mean value: 
[4.49577033 8.36220707 1.40351164]

and covariance matrix: 
[[ 8.61991175 -5.08030304  1.34832765]
 [-5.08030304  9.92945783  1.51063718]
 [ 1.34832765  1.51063718  7.37973086]]

Generated measurement 2 has mean value: 
[9.1091299  5.1019116  4.43913297]

and covariance matrix: 
[[ 5.11079882 -2.17417691 -0.55227383]
 [-2.17417691  3.06725646 -0.81344982]
 [-0.55227383 -0.81344982  3.57666577]]



In [2]:
# Now we use MCMC to produce the posterior distribution in different approaches.
def multivar_likelihood(x, mu, cov):
    diff = x - mu
    return -0.5 * np.dot(diff, np.linalg.solve(cov, diff))

# First attempt, combined sampling.
print("Now starting combined sampling.")
nwalkers = 2 * ndim
p0 = np.random.randn(nwalkers, ndim)
def combined_likelihood(x):
    return (multivar_likelihood(np.array([x[i] for i in dim_1]), mean_1, cov_1) +
            multivar_likelihood(np.array([x[i] for i in dim_2]), mean_2, cov_2) +
            multivar_likelihood(np.array([x[i] for i in dim_c]), mean_c, cov_c))

import emcee
nSamples = 100000
sampler = emcee.EnsembleSampler(nwalkers, ndim, combined_likelihood)
sampler.run_mcmc(p0, nSamples, progress=False)

samples = sampler.get_chain(flat=True, discard=int(nSamples/2))
print("Sampled mean values for (a, b): ({0}, {1}) \nand sigma values for (a, b): ({2}, {3})".format(
     np.mean(samples[:,0]), np.mean(samples[:,1]), np.var(samples[:,0]), np.var(samples[:,1])))

Now starting combined sampling.
Sampled mean values for (a, b): (7.319333998344855, 5.721772767737799) 
and sigma values for (a, b): (3.0868002325249773, 2.190737669806267)


In [3]:
# Second attempt, sequential sampling.
print("Now starting sequential sampling.")
from math import sqrt

# First measurement
def first_likelihood(x):
    return multivar_likelihood(x, mean_1, cov_1)

p0 = np.random.randn(nwalkers, len(mean_1))
sampler = emcee.EnsembleSampler(nwalkers, ndim-1, first_likelihood)
sampler.run_mcmc(p0, nSamples, progress=False)

samples = sampler.get_chain(flat=True, discard=int(nSamples/2))
mean_posterior = np.mean(samples, axis=0)
#print("Mean values from sampling the first measurement: \n", mean_posterior, "\n", sep="")

cov_posterior = np.cov(np.swapaxes(samples, 0, 1))
#print("Covariance matrix from sampling the first measurement: \n", cov_posterior, "\n", sep="")

# Corrected for calibration to form a prior for the second measurement
corr_posterior = np.corrcoef(np.swapaxes(samples, 0, 1))
#print("Correlation matrix from sampling the first measurement: \n", corr_posterior, "\n", sep="")

std_posterior = np.array([np.std(samples[:, par]) for par in range(len(mean_1))])
#print("Posterior standard deviation: ", std_posterior, sep="")

cov_prior = np.zeros(cov_2.shape) # need a mapping from (a, b, c) to (a, b, d)

# We could, of course, write down a fancy mapping function to handle the 
# parameters to be integrated out, but here we simply manually set the values.

for i in range(2):
    for j in range(2):
        cov_prior[i][j] = cov_posterior[i][j] # unaltered part

std_2 = sqrt(std_posterior[2]**2 * corr_c[0][1]**2 * cov_c[1][1] / cov_c[0][0]
            + cov_c[1][1] * (1-corr_c[0][1]**2)) # \sigma_2^\prime

for i in range(2):
    rho = corr_posterior[i][2] * corr_c[0][1]
    cov_prior[i][2] = rho * std_2 * std_posterior[i]
    cov_prior[2][i] = rho * std_2 * std_posterior[i]

cov_prior[2][2] = std_2**2
#print("Mapped covariance matrix with calibration:\n", cov_prior, sep="")

# The mean value of d as prior
mean_prior = np.array([iValue for iValue in mean_posterior]) # a deep copy
mean_prior[2] = mean_c[1] - (mean_c[0] - mean_posterior[2]) * corr_c[0][1] * sqrt(cov_c[1][1] / cov_c[0][0]) # \mu_2^\prime

# Sampling the second measurement with a proper prior
def second_likelihood(x):
    return (multivar_likelihood(x, mean_prior, cov_prior) + # prior
            multivar_likelihood(x, mean_2, cov_2))

p0 = np.random.randn(nwalkers, len(mean_2))
sampler = emcee.EnsembleSampler(nwalkers, ndim-1, second_likelihood)
sampler.run_mcmc(p0, nSamples, progress=False)
samples = sampler.get_chain(flat=True, discard=int(nSamples/2))
print("Sampled mean values for (a, b): ({0}, {1}) \nand sigma values for (a, b): ({2}, {3})".format(
     np.mean(samples[:,0]), np.mean(samples[:,1]), np.var(samples[:,0]), np.var(samples[:,1])))

Now starting sequential sampling.
Sampled mean values for (a, b): (7.293393766477657, 5.740462414549517) 
and sigma values for (a, b): (3.1614457404845777, 2.2283478862546127)
